markdown:   redcarpet

permalink:  pretty
title:      Brandon Atkinson
url:        brandon.acknsyn.com

author:     
    name:   'Brandon Atkinson'
    url:    https://twitter.com/gorjusborg

paginate:   1

github:
    repo:   github.com/brandon-atkinson/brandon-atkinson.github.io

pages_list: {'About':'/about', 'Archive':'/archive', 'Feed':'/atom.xml'}
